import type { Metadata } from "next";
import "./globals.scss";
import SmoothScrollProvider from "@/providers/smooth scroll";
import { EdgeStoreProvider } from "@/libs/edgestore";

export const metadata: Metadata = {
  title: {
    template: "%s | spider verse",
    default: "spider verse",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <SmoothScrollProvider>
          <EdgeStoreProvider>{children}</EdgeStoreProvider>
        </SmoothScrollProvider>
      </body>
    </html>
  );
}
