import type { Metadata } from "next";
import SmoothScrollProvider from "@/providers/smooth scroll";
import { EdgeStoreProvider } from "@/libs/edgestore";
import { ToastContainer } from "react-toastify";


import 'react-toastify/dist/ReactToastify.css';
import "./globals.scss";

export const metadata: Metadata = {
  title: {
    template: "%s | spider verse",
    default: "spider verse",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <SmoothScrollProvider>
          <EdgeStoreProvider>
            {children}
            <ToastContainer
              position="top-center"
              autoClose={3000}
              hideProgressBar={false}
              newestOnTop={false}
              closeOnClick
              rtl={false}
              pauseOnFocusLoss
              draggable
              pauseOnHover
              theme="colored"
            />
          </EdgeStoreProvider>
        </SmoothScrollProvider>
      </body>
    </html>
  );
}
